steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/barnesas2/flask-app:v2', '.']
  
  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/barnesas2/flask-app:v2']

  # Step 3: Update the Compute Engine instance with the new Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'update', 'barnesas2', '--zone=us-east1', '--image=gcr.io/$PROJECT_ID/barnesas2/flask-app:v2']
